w05/d02/custom_params/isdb_starter_code/config/routes.rb
Rails.application.routes.draw do
  root "heroes#index"

  get "heroes/sort"
	resources :heroes, only: [:index, :show]
end

w05/d02/custom_params/isdb_starter_code/app/models/hero.rb
class Hero < ActiveRecord::Base
  def to_partial_path
    'heroes/hero'
  end
end

w05/d02/custom_params/isdb_starter_code/app/controllers/heroes_controller.rb
class HeroesController < ApplicationController
  @@descending = false
  @@prior_list

  def index
    if params[:query]
      search_by = params[:search].to_sym
      hero_list = Hero.all
      query = params[:query]
      @heroes = []
      hero_list.each do |hero|
        if hero[search_by].downcase.include? query.downcase
          @heroes << hero
        end
      end
      return @heroes
    end
    @paginate = true
    @heroes = Hero.page(params[:page]).per(5)
  end

  def show
    if params[:commit] == "Next"
      hero = Hero.find(params[:id].to_i + 1)
      redirect_to hero_path(hero)
    elsif params[:commit] == "Prev"
      hero = Hero.find(params[:id].to_i - 1)
      redirect_to hero_path(hero)
    elsif params[:commit] == "Go"
      @hero = Hero.find(params[:hero_id])
    else
      @hero = Hero.find(params[:id])
    end
  end

  def sort
    @heroes = Hero.order(params[:sort_by])
    if @@descending
      @heroes = Hero.order(params[:sort_by] + " desc")
    end
    @@descending = !@@descending
    render :index
  end

end

w05/d02/custom_params/isdb_starter_code/app/helpers/heroes_helper.rb
module HeroesHelper
end

w05/d02/custom_params/isdb_starter_code/app/views/heroes/_hero.html.erb
<tr class="hover">
  <td><%= hero.name %></td>
  <td><%= hero.identity %></td>
  <td><%= hero.powers %></td>
  <td><%= hero.location %></td>
</tr>

w05/d02/custom_params/isdb_starter_code/app/views/heroes/index.html.erb
<div class="container">
  <h3> Good Morning you beautiful evil genius</h3>
  <p> Heres the current information on those meddling superheroes</p>
  <br>
  <%= form_tag('/', method: 'get') do %>
    Search Superhero by
    <%= select_tag "search", options_for_select(["name", "identity", "powers", "location"]) %>
    : <%=text_field_tag :query %>
    <%= submit_tag "Search", "class" => "btn btn-primary"%>
  <% end %>

  <% if @paginate %>
    <%= paginate @heroes %>
  <% end %>

  <h3>Superhero Data</h3>
  <table class="table table-striped">
    <tr>
      <th><%= link_to "Name", heroes_sort_path(sort_by: "name") %></th>
      <th><%= link_to "Alias Supposedely", heroes_sort_path(sort_by: "identity") %></th>
      <th><%= link_to "Superpower", heroes_sort_path(sort_by: "powers") %></th>
      <th><%= link_to "Location...maybe", heroes_sort_path(sort_by: "location") %></th>
    </tr>
    <% @heroes.each do |hero| %>
      <tr>
        <td>
          <%= link_to '<button class="btn btn-primary">&nbsp;</button>'.html_safe, hero_path(hero) %>
          <span class="name">&nbsp;&nbsp;<%= hero.name %></span>
        </td>
        <td><%= hero.identity %></td>
        <td><%= hero.powers %></td>
        <td><%= hero.location %></td>
      </tr>
    <% end %>
  </table>
</div>

w05/d02/custom_params/isdb_starter_code/app/views/heroes/show.html.erb
<div class="container">

  <%= form_tag(hero_path, method:"get") do %>
    See another superhero (by id) <%= text_field_tag :hero_id %>
    <%= submit_tag "Go", "class" => "btn btn-primary" %>
  <% end %>
  <%= form_tag hero_path, method: 'get' do %>
    <%= submit_tag "Prev", "class" => "btn btn-primary" %>
    <%= submit_tag "Next", "class" => "btn btn-primary" %>
  <% end %>

  <h1><%= @hero.name %></h1>
  <h5><%= "#{@hero.name} is #{@hero.description} with #{@hero.powers} abilities."%></h5>

  <h3>Superhero Data</h3>
  <table class="table table-striped">
      <%= cache @hero do %>
    <tr>
      <th>Alias</th>
      <td><%= @hero.identity %></td>
    </tr>
    <tr>
      <th>Last Known Location</th>
      <td><%= @hero.location %></td>
    </tr>
    <tr>
      <th>Power</th>
      <td><%= @hero.powers %></td>
    </tr>
    <tr>
      <th>Weakness</th>
      <td><%= @hero.weakness %></td>
    </tr>
    <tr>
      <th>Stance</th>
      <td><%= @hero.description %></td>
    </tr>
    <tr>
      <th>Arch-Nemesis</th>
      <td><%= @hero.nemesis %></td>
    </tr>
      <% end %>
  </table>
</div>