w04/weekend/gyftrly/config/routes.rb
Rails.application.routes.draw do

  root 'gifts#index'

  get 'gifts/' => 'gifts#index', as: :gifts
  get 'gifts/sort/title' => 'gifts#sort_title', as: :gifts_title
  get 'gifts/sort/friend' => 'gifts#sort_friend', as: :gifts_friend
  get 'gifts/sort/price' => 'gifts#sort_price', as: :gifts_price
  get 'gifts/sort/purchased' => 'gifts#sort_purchased', as: :gifts_purchased

  get 'gifts/new' => 'gifts#new', as: :new_gift
  post 'gifts/' => 'gifts#create'

  get 'gifts/:id/edit' => 'gifts#edit', as: :edit_gift
  patch 'gifts/:id' => 'gifts#update'

  get 'gifts/:id' => 'gifts#show', as: :gift
  delete 'gifts/:id' => 'gifts#destroy'

end

w04/weekend/gyftrly/app/models/gift.rb
class Gift < ActiveRecord::Base
end

w04/weekend/gyftrly/app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  private
  attr_accessor :sorted_by

  public
  attr_accessor :gifts
  @gift
  @gifts
  @gift_total

#############################GETTER METHODS#############################
  def gifts
    @gifts = merge_sort(Gift.all, "title")
    self.gift_total
  end

  def gift_total
    total = 0
    @gifts.each do |gift|
      total += gift.price
      @gift_total = total
    end
  end
##################################SORT##################################

  def sort_title
    self.gifts
  end

  def sort_friend
    self.gifts = merge_sort self.gifts, "friend"
  end

  def sort_price
    self.gifts = merge_sort(self.gifts, "price")
  end

  def sort_purchased
    front_list = []
    end_list = []
    self.gifts.each do |gift, index|
      if gift.is_purchased
        front_list.push(gift)
      else
        end_list.push(gift)
      end
    end
    self.gifts = (front_list << end_list).flatten!
  end

#############################SERVER METHODS#############################
  def index
    self.gifts
  end

  def show
    puts "GIFT!!"
    puts @gift
    gift
    puts @gift
  end

  def edit
    gift
  end

  def new
    @gift = Gift.new
  end

  def create
    # gift_params is a custom private method for shorter code
    @gift = Gift.new(gift_params)

    if is_valid? @gift
      if @gift.save
        return redirect_to gift_path(@gift)
      end
    end
    render :new
  end

  def update
    gift
    updated_gift = @gift
    updated_gift.update_attributes(gift_params)
    if is_valid?(updated_gift)
      if @gift.update_attributes(gift_params)
        return redirect_to gift_path(@gift)
      end
    end
    render :edit
  end

  def destroy
    gift.destroy
    redirect_to gifts_path
  end

###########################PRIVATE METHODS##############################
  private

  def gift
    @gift = Gift.find(params[:id])
  end

  def is_valid? gift
    if gift.title != ""
      if gift.recipient != ""
        if gift.image_url != ""
          if gift.description != ""
            if gift.price.is_a? Numeric
              if !!gift.is_purchased == gift.is_purchased
                return true
              end
            end
          end
        end
      end
    end
    return false
  end

  def gift_params
    params.require(:gift).permit(:title, :recipient, :image_url, :description, :is_purchased, :price)
  end

  def merge_sort(lst, sort_by)
    self.sorted_by = sort_by
    if lst.length <= 1
      lst
    else
      mid = (lst.length / 2).floor
      left = merge_sort(lst[0..mid - 1], sort_by)
      right = merge_sort(lst[mid..lst.length], sort_by)
      merge(left, right, sort_by)
    end
  end

  def merge(left, right, sort_by)
    if left.empty?
      return right
    elsif right.empty?
      return left
    end

    if sort_by == "title"
      left_side = left.first.title
      right_side = right.first.title
    elsif sort_by == "friend"
      left_side = left.first.recipient
      right_side = right.first.recipient
    elsif sort_by == "price"
      left_side = left.first.price
      right_side = right.first.price
    end

    if left_side < right_side
      [left.first] + merge(left[1..left.length], right, sort_by)
    else
      [right.first] + merge(left, right[1..right.length], sort_by)
    end
  end

end

w04/weekend/gyftrly/app/helpers/gifts_helper.rb
module GiftsHelper
end

w04/weekend/gyftrly/app/views/gifts/edit.html.haml
%h1.text-center Edit Gift
%br

%div.form-container
  = render "partials/form"

%br
%div.text-center
  = link_to "Back", gift_path

w04/weekend/gyftrly/app/views/gifts/index.html.haml
= render "partials/sort"

w04/weekend/gyftrly/app/views/gifts/new.html.haml
%h1.text-center Add New Gift
%br

/ = form_for @gift, url: new_gift_path, html: { method: :put } do |f|
%div.form-container
  = render "partials/form"
%br
%div.text-center
  = link_to "Go Back", gifts_path

w04/weekend/gyftrly/app/views/gifts/show.html.haml
%h1.text-center For #{@gift.recipient}
%div.text-center
  = image_tag "#{@gift.image_url}", style: "max-width: 100px; height: auto"
%p.show-gift #{@gift.title} costs $#{@gift.price}
%p.text-center #{@gift.description}

%div.text-center
  %br
  %span
    = link_to "Back", gifts_path
  |
  %span
    = link_to "Edit", edit_gift_path
  |
  %span
    = link_to "Delete", gift_path, method: :delete

w04/weekend/gyftrly/app/views/gifts/sort_friend.html.haml
= render "partials/sort"

w04/weekend/gyftrly/app/views/gifts/sort_price.html.haml
= render "partials/sort"

w04/weekend/gyftrly/app/views/gifts/sort_purchased.html.haml
= render "partials/sort"

w04/weekend/gyftrly/app/views/gifts/sort_title.html.haml
= render "partials/sort"

w04/weekend/gyftrly/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Gyftrly
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield
  %br
  %br
  / %footer.text-center Footer goes here

w04/weekend/gyftrly/app/views/partials/_form.html.haml
= form_for @gift do |f|
  %div.form-group
    = f.text_field :recipient, :placeholder => "Recipient", :class => "form-control"
  %div.form-group
    = f.text_field :title, :placeholder => "Gift Name", :class => "form-control"
  %div.form-group
    = f.text_field :price, :placeholder => "Price", :class => "form-control"
  %div.form-group
    = f.text_field :image_url, :placeholder => "Image URL", :class => "form-control"
  %div.form-group
    = f.text_area :description, :rows => "4", :placeholder => "Description", :class => "form-control"
  %div.form-group.text-center
    = f.label "Purchased?"
    = f.check_box :is_purchased

  %br
  = f.submit :class => "submit-form-button"

w04/weekend/gyftrly/app/views/partials/_sort.html.haml
%h1.text-center Gift List
%br
%table.table.table-hover.table-striped
  %tr
    %th.col-md-1
    %th.col-md-2.text-info= link_to "Gift", gifts_title_path
    %th.col-md-2.link-success= link_to "Friend", gifts_friend_path
    %th.col-md-2.text-warning.text-center= link_to "Purchased", gifts_purchased_path
    %th.col-md-2.text-danger.text-right= link_to "Price", gifts_price_path
    %th.col-md-1
  - @gifts.each do |gift|
    %tr
      %td
      %td.text-info= link_to "#{gift.title}", gift_path(gift)
      %td.text-success #{gift.recipient}
      - purchased = "No"
      - purchased = "Yes" if gift.is_purchased
      %td.text-warning.text-center #{purchased}
      %td.text-danger.text-right $#{gift.price}
      %td
  %tr
    %td
    %td
    %td
    %td
    %td.text-right.text-danger
      %strong
        $#{@gift_total}
    %td

%div.text-center.text-success
  = link_to "Add new Gift", new_gift_path

w04/weekend/gyftrly/app/views/partials/sort_purchased.html.haml
= render "partials/sort"